name: build
on:
  push:
    branches: [ master ]
jobs:
  test-independent-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE && make
      - run: timeout 1 $GITHUB_WORKSPACE/main %GITHUB_WORKSPACE/target.c
